web:
  build: .
  links:
    - db
  ports:
    - "1337:1337"
  environment:
    NODE_ENV: development
  volumes:
    - .:/home/sails
    - /home/sails/node_modules

db:
  image: mongo
  ports:
    - "27017:27017"